apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: etherealpods.sunday.example.com
spec:
  group: sunday.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              template:
                type: object
                description: PodSpec template for the managed Pod
                x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              podName:
                type: string
                description: Name of the managed Pod
              restartCount:
                type: integer
                description: Total number of restarts
              age:
                type: string
                format: date-time
                description: Creation timestamp
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: AGE
      type: date
      description: Creation timestamp
      jsonPath: .metadata.creationTimestamp
    - name: RESTARTS
      type: integer
      description: Total number of restarts
      jsonPath: .status.restartCount
  scope: Namespaced
  names:
    plural: etherealpods
    singular: etherealpod
    kind: EtherealPod
    shortNames:
    - eps
