apiVersion: sunday.example.com/v1
kind: EtherealPod
metadata:
  name: test-restart-etherealpod
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: test-container
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args: ["sleep 5; exit 1"]
        # This container will exit with error code 1 after 5 seconds
        # Kubernetes will restart it, and the restart count should increment
